package proxy

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"regexp"
	"strings"
)

// ──────────────────────────────────────────────────────────────────
// Model family detection
// ──────────────────────────────────────────────────────────────────

type modelFamily int

const (
	familyAnthropic modelFamily = iota
	familyOpenAI
	familyGemini
	familyOther
)

func detectModelFamily(model string) modelFamily {
	m := strings.ToLower(model)
	switch {
	case strings.HasPrefix(m, "opus") || strings.HasPrefix(m, "sonnet") || strings.HasPrefix(m, "haiku") || strings.Contains(m, "claude"):
		return familyAnthropic
	case strings.HasPrefix(m, "gpt") || strings.HasPrefix(m, "o1") || strings.HasPrefix(m, "o3") || strings.HasPrefix(m, "o4"):
		return familyOpenAI
	case strings.HasPrefix(m, "gemini"):
		return familyGemini
	default:
		return familyOther
	}
}

// ──────────────────────────────────────────────────────────────────
// Format-specific tool definition builders
// ──────────────────────────────────────────────────────────────────

// buildAnthropicToolsBlock generates Anthropic-style <tools> block (native to Claude)
func buildAnthropicToolsBlock(tools []Tool) string {
	type anthropicTool struct {
		Name        string      `json:"name"`
		Description string      `json:"description,omitempty"`
		InputSchema interface{} `json:"input_schema"`
	}
	var defs []anthropicTool
	for _, t := range tools {
		schema := t.Function.Parameters
		if schema == nil {
			schema = map[string]interface{}{"type": "object", "properties": map[string]interface{}{}}
		}
		defs = append(defs, anthropicTool{
			Name:        t.Function.Name,
			Description: t.Function.Description,
			InputSchema: schema,
		})
	}
	data, _ := json.MarshalIndent(defs, "", "  ")
	return fmt.Sprintf("<tools>\n%s\n</tools>", string(data))
}

// buildOpenAIToolsBlock generates OpenAI-style functions block (native to GPT)
func buildOpenAIToolsBlock(tools []Tool) string {
	type openaiFunc struct {
		Name        string      `json:"name"`
		Description string      `json:"description,omitempty"`
		Parameters  interface{} `json:"parameters"`
	}
	var funcs []openaiFunc
	for _, t := range tools {
		params := t.Function.Parameters
		if params == nil {
			params = map[string]interface{}{"type": "object", "properties": map[string]interface{}{}}
		}
		funcs = append(funcs, openaiFunc{
			Name:        t.Function.Name,
			Description: t.Function.Description,
			Parameters:  params,
		})
	}
	data, _ := json.MarshalIndent(funcs, "", "  ")
	return fmt.Sprintf("## Functions\n```json\n%s\n```", string(data))
}

// buildGeminiToolsBlock generates Google-style function declarations (native to Gemini)
func buildGeminiToolsBlock(tools []Tool) string {
	type geminiFunc struct {
		Name        string      `json:"name"`
		Description string      `json:"description,omitempty"`
		Parameters  interface{} `json:"parameters"`
	}
	var funcs []geminiFunc
	for _, t := range tools {
		params := t.Function.Parameters
		if params == nil {
			params = map[string]interface{}{"type": "object", "properties": map[string]interface{}{}}
		}
		funcs = append(funcs, geminiFunc{
			Name:        t.Function.Name,
			Description: t.Function.Description,
			Parameters:  params,
		})
	}
	data, _ := json.MarshalIndent(funcs, "", "  ")
	return fmt.Sprintf("Available function declarations:\n%s", string(data))
}

// buildToolsBlock is retained for callers that need a standalone schema block.
// The active client bridge uses buildToolBridgeContract instead, so this
// legacy formatter is not inserted into every request.
func buildToolsBlock(tools []Tool, family modelFamily) string {
	return buildOpenAIToolsBlock(tools)
}

// ──────────────────────────────────────────────────────────────────
// Stable tool bridge contract and request directives
// ──────────────────────────────────────────────────────────────────

// buildToolList preserves the complete client-provided description and schema.
func buildToolList(tools []Tool) string {
	var sb strings.Builder
	for _, t := range tools {
		sb.WriteString(fmt.Sprintf("Label: %s", t.Function.Name))
		if t.Function.Description != "" {
			sb.WriteString(fmt.Sprintf(" - %s", t.Function.Description))
		}
		if t.Function.Parameters != nil {
			params, _ := json.Marshal(t.Function.Parameters)
			sb.WriteString(fmt.Sprintf("\nArgument schema: %s", string(params)))
		}
		sb.WriteString("\n")
	}
	return sb.String()
}

func buildSizedToolList(tools []Tool) (list string, compacted bool, fullBytes int) {
	full := buildToolList(tools)
	return full, false, len(full)
}

// toolBridgeContractMarker identifies text generated by this gateway. The
// marker is deliberately explicit so migration code can distinguish the
// bridge contract from user-authored content without fuzzy deletion.
const toolBridgeContractMarker = "[notion-manager tool bridge contract v1]"

// toolBridgeFingerprint identifies the complete aliased tool contract. Tool
// order is significant because aliases (action_1, action_2, ...) are assigned
// in that order and are part of the model-visible protocol.
func toolBridgeFingerprint(tools []Tool, workingDirectories ...string) string {
	payload := struct {
		Tools            []Tool `json:"tools"`
		WorkingDirectory string `json:"working_directory,omitempty"`
	}{
		Tools:            tools,
		WorkingDirectory: firstNonEmptyString(workingDirectories),
	}
	encoded, _ := json.Marshal(payload)
	sum := sha256.Sum256(encoded)
	return hex.EncodeToString(sum[:])[:24]
}

// buildToolBridgeContract creates the one stable bridge instruction that is
// stored at the beginning of a Notion thread. It intentionally contains no
// current REQUEST/ROUTES framing: later turns are sent as ordinary user
// messages and the model keeps using this contract from the thread context.
func buildToolBridgeContract(tools []Tool, update bool, workingDirectories ...string) string {
	intro := "This is the stable tool contract for the client conversation. It is bridge configuration, not a user request. " +
		"Do not answer this entry; keep it active for every later user message."
	if update {
		intro = "This is an updated stable tool contract for the client conversation. It replaces the previous tool contract. " +
			"Do not answer this entry; keep this version active for every later user message."
	}
	workingDirectoryLine := ""
	if workingDirectory := firstNonEmptyString(workingDirectories); workingDirectory != "" {
		workingDirectoryLine = fmt.Sprintf("\nWorking directory: %s", workingDirectory)
	}
	return fmt.Sprintf(
		"%s\n%s%s\n\n"+
			"In auto mode, answer directly in natural language when no external operation is needed. "+
			"When a listed tool is needed, return exactly one JSON object of the form "+
			"{\"name\":\"label\",\"arguments\":{...}} and do not add commentary. "+
			"Use only the labels and argument schemas below. After a completed tool result, continue from that result; "+
			"answer naturally when it is sufficient or return another valid tool JSON object when another operation is needed. "+
			"Never claim that an operation succeeded before a completed result is supplied.\n\n"+
			"Available tools:\n%s",
		toolBridgeContractMarker, intro, workingDirectoryLine, buildToolList(tools))
}

// addToolBridgeDirective adds a small per-request mode override without
// repeating the full contract. It returns a copy and never mutates the
// caller's client-visible message history.
func addToolBridgeDirective(messages []ChatMessage, directive string) []ChatMessage {
	directive = strings.TrimSpace(directive)
	if directive == "" {
		return cloneChatMessages(messages)
	}
	result := cloneChatMessages(messages)
	lastAssistant := -1
	for i := len(result) - 1; i >= 0; i-- {
		if result[i].Role == "assistant" {
			lastAssistant = i
			break
		}
	}
	// Attach the override to the current client turn only. In a tool
	// continuation the newest input is a tool result (Role=tool), so looking
	// through the whole history would incorrectly modify an old user message
	// that partial-transcript mode does not send again.
	for i := len(result) - 1; i >= 0; i-- {
		if i <= lastAssistant {
			break
		}
		if result[i].Role == "user" && result[i].ToolCallID == "" {
			if strings.TrimSpace(result[i].Content) == "" {
				result[i].Content = directive
			} else {
				result[i].Content = directive + "\n\n" + result[i].Content
			}
			return result
		}
	}
	// Keep a mode override visible to buildPartialContinuationContent even
	// when the current tail contains only tool results.
	return append(result, ChatMessage{Role: "user", Content: directive})
}

func toolBridgeDirective(toolChoiceMode string, aliases map[string]string) string {
	switch {
	case toolChoiceMode == "required":
		return "Tool mode for this request: a tool call is required. Return exactly one valid tool JSON object and do not answer with ordinary prose."
	case strings.HasPrefix(toolChoiceMode, "force:"):
		name := strings.TrimPrefix(toolChoiceMode, "force:")
		if alias, ok := aliases[name]; ok {
			name = alias
		}
		return fmt.Sprintf("Tool mode for this request: call exactly %q and return one valid tool JSON object.", name)
	default:
		return ""
	}
}

func extractToolBridgeWorkingDirectory(messages []ChatMessage) string {
	cwdPattern := regexp.MustCompile(`<cwd>([^<]+)</cwd>`)
	for _, message := range messages {
		if message.Role != "system" {
			continue
		}
		if match := cwdPattern.FindStringSubmatch(message.Content); len(match) >= 2 {
			return strings.TrimSpace(match[1])
		}
	}
	return ""
}

func isSuggestionMode(content string) bool {
	return strings.HasPrefix(strings.TrimSpace(content), "[SUGGESTION MODE:")
}

func isToolBridgeSuggestionMode(messages []ChatMessage) bool {
	for i := len(messages) - 1; i >= 0; i-- {
		message := messages[i]
		if message.Role != "user" || message.ToolCallID != "" || strings.TrimSpace(message.Content) == "" {
			continue
		}
		return isSuggestionMode(message.Content)
	}
	return false
}

func aliasClientTools(tools []Tool) ([]Tool, map[string]string, map[string]string) {
	if len(tools) == 0 {
		return tools, nil, nil
	}

	aliased := make([]Tool, len(tools))
	originalToAlias := make(map[string]string, len(tools))
	aliasToOriginal := make(map[string]string, len(tools))
	for i, tool := range tools {
		alias := fmt.Sprintf("action_%d", i+1)
		original := tool.Function.Name
		aliased[i] = tool
		aliased[i].Function = tool.Function
		aliased[i].Function.Name = alias
		aliased[i].Function.Description = strings.ReplaceAll(tool.Function.Description, original, alias)
		originalToAlias[original] = alias
		aliasToOriginal[alias] = original
	}
	return aliased, originalToAlias, aliasToOriginal
}

func aliasToolNamesInMessages(messages []ChatMessage, originalToAlias map[string]string) []ChatMessage {
	if len(originalToAlias) == 0 {
		return messages
	}
	for i := range messages {
		if alias, ok := originalToAlias[messages[i].Name]; ok {
			messages[i].Name = alias
		}
		for j := range messages[i].ToolCalls {
			if alias, ok := originalToAlias[messages[i].ToolCalls[j].Function.Name]; ok {
				messages[i].ToolCalls[j].Function.Name = alias
			}
		}
	}
	return messages
}

func aliasToolChoice(toolChoice interface{}, originalToAlias map[string]string) interface{} {
	if toolChoice == nil || len(originalToAlias) == 0 {
		return toolChoice
	}
	choice, ok := toolChoice.(map[string]interface{})
	if !ok {
		return toolChoice
	}
	cloned := make(map[string]interface{}, len(choice))
	for key, value := range choice {
		cloned[key] = value
	}
	if name, ok := cloned["name"].(string); ok {
		if alias, exists := originalToAlias[name]; exists {
			cloned["name"] = alias
		}
	}
	if fn, ok := cloned["function"].(map[string]interface{}); ok {
		clonedFunction := make(map[string]interface{}, len(fn))
		for key, value := range fn {
			clonedFunction[key] = value
		}
		if name, ok := clonedFunction["name"].(string); ok {
			if alias, exists := originalToAlias[name]; exists {
				clonedFunction["name"] = alias
			}
		}
		cloned["function"] = clonedFunction
	}
	return cloned
}

// ──────────────────────────────────────────────────────────────────
// Claude Code compatibility bridge
// ──────────────────────────────────────────────────────────────────

// filterNativeSearchTools detects WebSearch without removing any client tool
// definition. WebSearch is intercepted by the proxy; WebFetch and every other
// tool are returned to the client through the normal compatibility bridge.
func filterNativeSearchTools(tools []Tool) ([]Tool, bool) {
	hasWebSearch := false
	for _, t := range tools {
		if t.Function.Name == "WebSearch" {
			hasWebSearch = true
		}
	}
	return tools, hasWebSearch
}

// stripSystemReminders removes Claude Code-specific XML wrapper tags from messages.
// These include:
// - <system-reminder>: identity reinforcement, skill lists, token usage
// - <local-command-caveat>: contains "DO NOT respond" which kills the response
// - Inline tags like <command-name>/clear</command-name>
var (
	blockTagRegex  = regexp.MustCompile(`(?s)<(?:system-reminder|local-command-caveat|available-deferred-tools)>.*?</(?:system-reminder|local-command-caveat|available-deferred-tools)>`)
	inlineTagRegex = regexp.MustCompile(`(?s)<(?:command-name|command-message|command-args)>.*?</(?:command-name|command-message|command-args)>`)
)

func stripSystemReminders(content string) string {
	content = blockTagRegex.ReplaceAllString(content, "")
	content = inlineTagRegex.ReplaceAllString(content, "")
	return strings.TrimSpace(content)
}

func resolveToolChoiceMode(toolChoice ...interface{}) string {
	mode := "auto"
	if len(toolChoice) == 0 || toolChoice[0] == nil {
		return mode
	}
	switch value := toolChoice[0].(type) {
	case string:
		switch strings.ToLower(strings.TrimSpace(value)) {
		case "none":
			return "none"
		case "required", "any":
			return "required"
		default:
			return "auto"
		}
	case map[string]interface{}:
		if function, ok := value["function"].(map[string]interface{}); ok {
			if name, _ := function["name"].(string); strings.TrimSpace(name) != "" {
				return "force:" + strings.TrimSpace(name)
			}
		}
		kind, _ := value["type"].(string)
		switch strings.ToLower(strings.TrimSpace(kind)) {
		case "any", "required":
			return "required"
		case "tool", "function":
			if name, _ := value["name"].(string); strings.TrimSpace(name) != "" {
				return "force:" + strings.TrimSpace(name)
			}
		case "none":
			return "none"
		}
	}
	return mode
}

// ──────────────────────────────────────────────────────────────────
// Tool call parsing: extract from NDJSON native tool_use or text
// ──────────────────────────────────────────────────────────────────

// nativeToolUseToOpenAI converts native Anthropic tool_use entries (from NDJSON) to OpenAI ToolCalls
func nativeToolUseToOpenAI(entries []AgentValueEntry) []ToolCall {
	var calls []ToolCall
	for i, e := range entries {
		if e.Type != "tool_use" || e.Name == "" {
			continue
		}
		argsStr := "{}"
		if len(e.Input) > 0 && json.Valid(e.Input) {
			argsStr = string(e.Input)
		}
		calls = append(calls, ToolCall{
			ID:   e.ID,
			Type: "function",
			Function: ToolCallFunction{
				Name:      e.Name,
				Arguments: argsStr,
			},
		})
		_ = i
	}
	return calls
}

// Regex-based fallback parsers for text-based tool call output
var toolCallXMLRegex = regexp.MustCompile(`(?s)<tool_call>\s*(\{.*?\})\s*</tool_call>`)
var mdFenceRegex = regexp.MustCompile("(?s)```(?:json|tool_call)?\\s*\\n?(.*?)\\n?```")
var jsonToolCallRegex = regexp.MustCompile(`(?s)\{"tool_call"\s*:\s*(\{.*?\})\s*\}`)

// parseToolCalls extracts tool calls from model response text (fallback when native tool_use not available).
// Returns (toolCalls, remainingText, hasToolCalls)
func parseToolCalls(content string) ([]ToolCall, string, bool) {
	var toolCalls []ToolCall
	remaining := content

	// Method 1: <tool_call>{...}</tool_call> XML format (preferred)
	xmlMatches := toolCallXMLRegex.FindAllStringSubmatch(content, -1)
	for i, match := range xmlMatches {
		remaining = strings.Replace(remaining, match[0], "", 1)
		tc := parseToolCallJSON(match[1], i)
		if tc != nil {
			toolCalls = append(toolCalls, *tc)
		}
	}
	if len(toolCalls) > 0 {
		return toolCalls, strings.TrimSpace(remaining), true
	}

	// Method 1.5: extract JSON from markdown fences (handles "text + ```json{...}```" output)
	remaining = content
	mdMatches := mdFenceRegex.FindAllStringSubmatch(content, -1)
	for i, match := range mdMatches {
		fenced := strings.TrimSpace(match[1])
		tc := parseToolCallJSON(fenced, i)
		if tc != nil {
			toolCalls = append(toolCalls, *tc)
			remaining = strings.Replace(remaining, match[0], "", 1)
		}
	}
	if len(toolCalls) > 0 {
		return toolCalls, strings.TrimSpace(remaining), true
	}

	// Method 1.7: balanced-brace scan for tool-call JSON embedded in prose,
	// including pretty-printed and multiple multi-line objects.
	if embedded := extractToolCallJSONBlocks(content); len(embedded) > 0 {
		remaining = content
		for _, block := range embedded {
			if tc := parseToolCallJSON(block, len(toolCalls)); tc != nil {
				toolCalls = append(toolCalls, *tc)
				remaining = strings.Replace(remaining, block, "", 1)
			}
		}
		if len(toolCalls) > 0 {
			return toolCalls, strings.TrimSpace(remaining), true
		}
	}

	// Method 2: direct JSON or {"tool_call": {...}} format
	remaining = content
	stripped := strings.TrimSpace(content)
	if strings.HasPrefix(stripped, "<|") {
		sentinelPayload := strings.TrimSpace(strings.TrimPrefix(stripped, "<|"))
		decoder := json.NewDecoder(strings.NewReader(sentinelPayload))
		var raw json.RawMessage
		if err := decoder.Decode(&raw); err == nil {
			if tc := parseToolCallJSON(string(raw), 0); tc != nil {
				rest := strings.TrimSpace(sentinelPayload[int(decoder.InputOffset()):])
				rest = strings.TrimSpace(strings.TrimPrefix(rest, "|>"))
				return []ToolCall{*tc}, rest, true
			}
		}
		stripped = strings.TrimSpace(strings.TrimSuffix(sentinelPayload, "|>"))
	}

	// Try direct {"name": "...", "arguments": {...}} format
	var direct struct {
		Name      string          `json:"name"`
		Arguments json.RawMessage `json:"arguments"`
	}
	if err := json.Unmarshal([]byte(stripped), &direct); err == nil && direct.Name != "" && len(bytes.TrimSpace(direct.Arguments)) > 0 {
		argsStr := string(direct.Arguments)
		if !json.Valid(direct.Arguments) {
			argsStr = "{}"
		}
		toolCalls = append(toolCalls, ToolCall{
			ID:   fmt.Sprintf("call_0_%s", generateUUIDv4()[:8]),
			Type: "function",
			Function: ToolCallFunction{
				Name:      direct.Name,
				Arguments: argsStr,
			},
		})
		return toolCalls, "", true
	}

	// Try {"tool_call": {...}} wrapper format
	var wrapper struct {
		ToolCall *struct {
			Name      string          `json:"name"`
			Arguments json.RawMessage `json:"arguments"`
		} `json:"tool_call"`
	}
	if err := json.Unmarshal([]byte(stripped), &wrapper); err == nil && wrapper.ToolCall != nil &&
		wrapper.ToolCall.Name != "" && len(bytes.TrimSpace(wrapper.ToolCall.Arguments)) > 0 {
		argsStr := string(wrapper.ToolCall.Arguments)
		if !json.Valid(wrapper.ToolCall.Arguments) {
			argsStr = "{}"
		}
		toolCalls = append(toolCalls, ToolCall{
			ID:   fmt.Sprintf("call_0_%s", generateUUIDv4()[:8]),
			Type: "function",
			Function: ToolCallFunction{
				Name:      wrapper.ToolCall.Name,
				Arguments: argsStr,
			},
		})
		return toolCalls, "", true
	}

	// Method 3: multi-line JSON — each line is a separate {"name":"...", "arguments":{...}}
	// This handles parallel tool calls output by the model
	lines := strings.Split(stripped, "\n")
	var multiCalls []ToolCall
	var nonToolLines []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		var lineCall struct {
			Name      string          `json:"name"`
			Arguments json.RawMessage `json:"arguments"`
		}
		if err := json.Unmarshal([]byte(line), &lineCall); err == nil && lineCall.Name != "" && len(bytes.TrimSpace(lineCall.Arguments)) > 0 {
			argsStr := string(lineCall.Arguments)
			if !json.Valid(lineCall.Arguments) {
				argsStr = "{}"
			}
			multiCalls = append(multiCalls, ToolCall{
				ID:   fmt.Sprintf("call_%d_%s", len(multiCalls), generateUUIDv4()[:8]),
				Type: "function",
				Function: ToolCallFunction{
					Name:      lineCall.Name,
					Arguments: argsStr,
				},
			})
		} else {
			nonToolLines = append(nonToolLines, line)
		}
	}
	if len(multiCalls) > 0 {
		return multiCalls, strings.TrimSpace(strings.Join(nonToolLines, "\n")), true
	}

	return nil, content, false
}

// extractToolCallJSONBlocks returns balanced top-level JSON objects that decode
// as {"name": ..., "arguments": ...} tool-call envelopes.
func extractToolCallJSONBlocks(text string) []string {
	var blocks []string
	for i := 0; i < len(text); i++ {
		if text[i] != '{' {
			continue
		}
		windowEnd := i + 256
		if windowEnd > len(text) {
			windowEnd = len(text)
		}
		if !strings.Contains(text[i:windowEnd], `"name"`) {
			continue
		}

		depth := 0
		inString := false
		escaped := false
		end := -1
		for j := i; j < len(text); j++ {
			ch := text[j]
			if escaped {
				escaped = false
				continue
			}
			if inString {
				if ch == '\\' {
					escaped = true
				} else if ch == '"' {
					inString = false
				}
				continue
			}
			switch ch {
			case '"':
				inString = true
			case '{':
				depth++
			case '}':
				depth--
				if depth == 0 {
					end = j + 1
				}
			}
			if end >= 0 {
				break
			}
		}
		if end < 0 {
			continue
		}
		candidate := text[i:end]
		var probe struct {
			Name      string          `json:"name"`
			Arguments json.RawMessage `json:"arguments"`
		}
		if json.Unmarshal([]byte(candidate), &probe) == nil && strings.TrimSpace(probe.Name) != "" && len(bytes.TrimSpace(probe.Arguments)) > 0 {
			blocks = append(blocks, candidate)
			i = end - 1
		}
	}
	return blocks
}
func parseToolCallJSON(jsonStr string, index int) *ToolCall {
	var call struct {
		Name      string          `json:"name"`
		Arguments json.RawMessage `json:"arguments"`
	}
	if err := json.Unmarshal([]byte(jsonStr), &call); err != nil || strings.TrimSpace(call.Name) == "" || len(bytes.TrimSpace(call.Arguments)) == 0 {
		return nil
	}
	argsStr := string(call.Arguments)
	if !json.Valid(call.Arguments) {
		argsStr = "{}"
	}
	return &ToolCall{
		ID:   fmt.Sprintf("call_%d_%s", index, generateUUIDv4()[:8]),
		Type: "function",
		Function: ToolCallFunction{
			Name:      call.Name,
			Arguments: argsStr,
		},
	}
}
